enum BulletinType {
  ABERTURA = 'ABERTURA',
  INTERMEDIÁRIO = 'INTERMEDIÁRIO',
  FECHAMENTO_INTERBANCÁRIO = 'FECHAMENTO INTERBANCÁRIO',
  FECHAMENTO_PTAX = 'FECHAMENTO PTAX',
}

export { BulletinType };
