enum CompanySize {
  MICRO_ENTERPRISE = 'MICRO EMPRESA',
  SMALL_ENTERPRISE = 'EMPRESA DE PEQUENO PORTE',
  MEDIUM_ENTERPRISE = 'EMPRESA DE MÉDIO PORTE',
  LARGE_ENTERPRISE = 'EMPRESA DE GRANDE PORTE',
  VERY_LARGE_ENTERPRISE = 'DEMAIS',
}

export { CompanySize };
